# Generated by Django 5.1.2 on 2024-10-23 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPageflows', '0002_alter_product_image_alter_product_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='media/videos/')),
                ('name', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_flows', to='myPageflows.product')),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/screenshots/')),
                ('user_flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='myPageflows.userflow')),
            ],
        ),
    ]
