# Generated by Django 5.1.2 on 2024-10-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPageflows', '0003_userflow_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='userflow',
            name='save_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
