# Generated by Django 5.1.2 on 2024-10-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPageflows', '0004_userflow_save_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userflow',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
    ]
