# Generated by Django 5.1.2 on 2024-10-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPageflows', '0006_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userflow',
            name='image',
            field=models.ImageField(default=1, upload_to='media/screenshots/'),
            preserve_default=False,
        ),
    ]
