# Generated by Django 5.1.2 on 2024-10-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPageflows', '0007_userflow_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userflow',
            name='logo',
            field=models.ImageField(null=True, upload_to='media/logo/'),
        ),
    ]
