# Generated by Django 5.1.2 on 2024-10-31 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPageflows', '0008_userflow_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userflow',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
