# Generated by Django 5.1.2 on 2024-10-31 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPageflows', '0010_remove_userflow_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userflow',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
