# Generated by Django 5.1.2 on 2024-10-31 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myPageflows', '0011_userflow_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userflow',
            name='view_count',
        ),
    ]
